name: figenie
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  weather: ^3.1.1
  simple_circular_progress_bar: ^1.0.2
  flutter_polyline_points: ^2.0.0
  maps_toolkit: ^3.0.0
  location: ^6.0.1
  get: ^4.6.6
  intl: ^0.19.0
  http: ^1.2.1
  geocoding: ^3.0.0
  carousel_slider: ^4.2.1
  confetti: ^0.7.0
  vibration: ^1.8.4
  flutter_map: ^7.0.0
  open_route_service: ^1.2.4
  latlong2: ^0.9.0
  flutter_map_animations: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/roamer_logo.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/
