// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKfaHjlpUrtsFbYAdiPeLdod9xtfOXzZo',
    appId: '1:894070539185:web:6382ff4a8d1b339cd77390',
    messagingSenderId: '894070539185',
    projectId: 'explorer-b3606',
    authDomain: 'explorer-b3606.firebaseapp.com',
    storageBucket: 'explorer-b3606.appspot.com',
    measurementId: 'G-82SMZFTJX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4WrQWRqdbIsP2viBfMJQuxOHd7GKrR-s',
    appId: '1:894070539185:android:ef0e0e98d848c7ded77390',
    messagingSenderId: '894070539185',
    projectId: 'explorer-b3606',
    storageBucket: 'explorer-b3606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqfRFeNezokgujQVCxov_TmfpVKjLBp-w',
    appId: '1:894070539185:ios:48c64e49ade7d817d77390',
    messagingSenderId: '894070539185',
    projectId: 'explorer-b3606',
    storageBucket: 'explorer-b3606.appspot.com',
    iosClientId: '894070539185-vc3q1tigkn9147k94lett3385jhu6ucr.apps.googleusercontent.com',
    iosBundleId: 'com.example.figenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqfRFeNezokgujQVCxov_TmfpVKjLBp-w',
    appId: '1:894070539185:ios:48c64e49ade7d817d77390',
    messagingSenderId: '894070539185',
    projectId: 'explorer-b3606',
    storageBucket: 'explorer-b3606.appspot.com',
    iosBundleId: 'com.example.figenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKfaHjlpUrtsFbYAdiPeLdod9xtfOXzZo',
    appId: '1:894070539185:web:273db7b770cded78d77390',
    messagingSenderId: '894070539185',
    projectId: 'explorer-b3606',
    authDomain: 'explorer-b3606.firebaseapp.com',
    storageBucket: 'explorer-b3606.appspot.com',
    measurementId: 'G-FWS80JBQXK',
  );
}